quarkus.messaging.nats.streams.test.name=test
quarkus.messaging.nats.streams.test.subjects=data

quarkus.messaging.nats.consumers.data-consumer.stream=test
quarkus.messaging.nats.consumers.data-consumer.name=data-consumer
quarkus.messaging.nats.consumers.data-consumer.filter-subject=data
quarkus.messaging.nats.consumers.data-consumer.durable=true
quarkus.messaging.nats.consumers.data-consumer.max-deliver=1

mp.messaging.outgoing.data.connector=quarkus-jetstream
mp.messaging.outgoing.data.stream=test
mp.messaging.outgoing.data.subject=data

mp.messaging.incoming.data-consumer.connector=quarkus-jetstream
mp.messaging.incoming.data-consumer.stream=test
mp.messaging.incoming.data-consumer.consumer=data-consumer